name: PlatformIO Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install platformIO libraries
        run: pio lib install

      - name: Create CONFIG_PRIVATE.h
        run: |
          touch $GITHUB_WORKSPACE/src/CONFIG_PRIVATE.h
          echo $'#define LORA_APP_EUI "<LORA_DEVICE_EUI>"\n#define LORA_APP_KEY "<LORA_DEVICE_APP_KEY>"' > $GITHUB_WORKSPACE/src/CONFIG_PRIVATE.h

      - name: Run PlatformIO
        run: platformio run